#..............................    L A B E L S            #

labels: 
  app:          <APP_NAME>

#..............................    S E R V I C E          #

service:
  name: <SERVICE_NAME>
  api: v1
  type: <SERVICE_TYPE>
  ports: 
    - name: https
      externalPort: <EXTERNAL_PORT>
      internalPort: <INTERNAL_PORT


#..............................   Deployment            #
image: 
  repository: <REPO_NAME>
  name: <IMAGE_NAME>
  tag: <IMAGE_TAG>
  pullPolicy: Always

deployment:
  name: <APP_NAME>
  api:  apps/v1beta1
  replicaCount: 1
  strategy: 
    rollingUpdateType: RollingUpdate
    maxUnavailable: 1
    maxSurge: 0

volumesMountsSecretDisabled: false
volumesSecretDisabled: false

containerCommandDisabled: false
container:  
   command: "flowcentral-bridge"

readinessProbeDisabled: true
readinessProbe:
  httpGetPath: <READINESS_PATH>
  httpGetPort: <READINESS_PORT>
  httpGetScheme: <READINESS_SCHEME>
  initialDelaySeconds: 60
  periodSeconds: 30
  successThreshold: 1
  timeoutSeconds: 1
  failureThreshold: 3

#didn't do a way to expose secrets as env because its a big security issue (and who is doing it this way should change to best practices)
envFromConfigMapDisabled: false
envFromValueDisabled: true

nodeSelectorDisabled: false
nodeSelector:
  - key   : kops.k8s.io/instancegroup
    value : "apps"

tolerationsDisabled: false
tolerations: 
  - effect:   "NoExecute"
    key:      "kops.k8s.io/instancegroup"
    operator: "Equal"
    value:    "apps"

securityContextDisabled: true
securityContext:
  fsGroup: 2000
  runAsNonRoot: true
  runAsUser: 1000

resourcesDisabled: false
resources:
  requests: 
    cpu: "256m"
    ephemeralStorage: "2Gi"
    memory: "1Gi"
  limits: 
    cpu: "512m"
    ephemeralStorage: "2Gi"
    memory: "2Gi"
  
#..............................   Persistent Volume Claim           #

persistence:
  enabled: false
  # storageClass: "-"
  accessMode: ReadWriteOnce
  size: 8Gi
  annotations: {}

#..............................   Ingress          #
ingress:
  enabled: false


#..............................   Config Map            #
configMap:
    name: <APP_NAME>
    data: 
      GET_HOSTS_FROM: env
