
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.deployment.name | quote }}
  namespace: {{ .Release.Namespace }}
{{- with .Values.persistence.annotations  }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    app: {{ .Values.labels.app | quote }}
    version: {{ .Values.labels.version | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
{{- range $key, $value := .Values.configMap.data }}
{{ toYaml $key | trim | indent 6 }}: {{ $value | quote }}
{{- end }}