version: '2.2'
services:
  flowmanager:
    image: <IMAGE_NAME>:<IMAGE_TAG>
    stdin_open: true
    hostname: "<FM_GENERAL_HOSTNAME>"
    tty: true
    environment:
        ### EULA ###
        ACCEPT_EULA: "<ACCEPT_EULA>"
        
        #General
        FM_GENERAL_FQDN                              : "<FM_GENERAL_FQDN>"
        FM_GENERAL_UI_PORT                           : "<FM_GENERAL_UI_PORT>"
        FM_GENERAL_ENCRYPTION_KEY                    : "<FM_GENERAL_ENCRYPTION_KEY>"
        FM_GENERAL_LOGGING_LEVEL                     : "<FM_GENERAL_LOGGING_LEVEL>"
        #FM_GENERAL_LICENSE                           : "<FM_GENERAL_LICENSE>"
        FM_LOGS_CONSOLE                              : "<FM_LOGS_CONSOLE>"
        FM_GENERAL_CUSTOM_LOCATION_PATH              : "<FM_GENERAL_CUSTOM_LOCATION_PATH>"

        #HTTPS
        FM_HTTPS_USE_CUSTOM_CERT                     : "<FM_HTTPS_USE_CUSTOM_CERT>"
        FM_HTTPS_KEYSTORE                            : "<FM_HTTPS_KEYSTORE>"
        FM_HTTPS_CERT_ALIAS                          : "<FM_HTTPS_CERT_ALIAS>"
        FM_HTTPS_KEYSTORE_PASSWORD                   : "<FM_HTTPS_KEYSTORE_PASSWORD>"
        #optional, only if FM is installed in K8s/openshift and ssl termination is activated
        #FM_HTTPS_DISABLED                           : "<FM_HTTPS_DISABLED>"
        
        #Redis
        FM_REDIS_ENABLED                             : "<FM_REDIS_ENABLED>"
        FM_REDIS_HOSTNAME                            : "<FM_REDIS_HOSTNAME>"
        FM_REDIS_PORT                                : "<FM_REDIS_PORT>"
        FM_REDIS_AUTH_ENABLED                        : "<FM_REDIS_AUTH_ENABLED>"
        FM_REDIS_PASSWORD                            : "<FM_REDIS_PASSWORD>"
        #optional,only for redis 6.x, it should be empty if not used
        FM_REDIS_USER                                : "<FM_REDIS_USER>"
        FM_REDIS_SSL_ENABLED                         : "<FM_REDIS_SSL_ENABLED>"
        #optional, it should be empty if redis ca is not set 
        FM_REDIS_SSL_CA                              : "<FM_REDIS_SSL_CA>"

        #Mongo
        FM_DATABASE_HOST                             : "<FM_DATABASE_HOST>"
        FM_DATABASE_PORT                             : "<FM_DATABASE_PORT>"
        #FM_DATABASE_NAME                             : "<FM_DATABASE_NAME>" # default database name if not set is umcft
        FM_DATABASE_USER_NAME                        : "<FM_DATABASE_USER_NAME>"
        FM_DATABASE_USER_PASSWORD                    : "<FM_DATABASE_USER_PASSWORD>"
        FM_DATABASE_USE_SSL                          : "<FM_DATABASE_USE_SSL>"
        FM_DATABASE_CERTIFICATES                     : "<FM_DATABASE_CERTIFICATES>"

        #GOVERNANCE
        FM_GOVERNANCE_CA_CERTIF_ALIAS                : "<FM_GOVERNANCE_CA_CERTIF_ALIAS>"
        FM_GOVERNANCE_CA_FILE                        : "<FM_GOVERNANCE_CA_FILE>"
        FM_GOVERNANCE_CA_PASSWORD                    : "<FM_GOVERNANCE_CA_PASSWORD>"
        
        #For Upgrade: Business (optional, it can be ser using rest api)
        #FM_BUSINESS_CA_CERTIF_ALIAS                  : "<FM_BUSINESS_CA_CERTIF_ALIAS>"
        #FM_BUSINESS_CA_FILE                          : "<FM_BUSINESS_CA_FILE>"
        #FM_BUSINESS_CA_PASSWORD                      : "<FM_BUSINESS_CA_PASSWORD>"
        
        #CFT (optional, for cft backward compatibility, it could be set also using rest api)
        FM_CFT_SHARED_SECRET                         : "<FM_CFT_SHARED_SECRET>"

        #JVM
        FM_JVM_XMX                                   : "<FM_JVM_XMX>"
        FM_JVM_XMS                                   : "<FM_JVM_XMS>"
        FM_JVM_XMN                                   : "<FM_JVM_XMN>"
        FM_JVM_DEBUG_ENABLED                         : "<FM_JVM_DEBUG_ENABLED>"
        FM_JVM_DEBUG_PORT                            : "<FM_JVM_DEBUG_PORT>"
        FM_JVM_DEBUG_SUSPEND                         : "<FM_JVM_DEBUG_SUSPEND>"                          
       
        #SAAS only environment variable
        #FM_GENERAL_SAAS_MODE                         : "<FM_GENERAL_SAAS_MODE>"
        #FM_GENERAL_HTTP_PORT                         : "<FM_GENERAL_HTTP_PORT>"
        #FM_ARS_HTTPONLY                              : "<FM_ARS_HTTPONLY>"
        #Platform 
        #FM_PLATFORM_HOST                             : "<FM_PLATFORM_HOST>"
        #Operations - on Saas only
        #FM_OPERATIONS_ADMIN_CLIENTID: "<FM_OPERATIONS_ADMIN_CLIENTID>"
        # Proxy for SaaS Mode
        #FM_PROXY_ENABLED                              : "<FM_PROXY_ENABLED>"
        #FM_PROXY_HOST                                 : "<FM_PROXY_HOST>"
        #FM_PROXY_PORT                                 : "<FM_PROXY_PORT>"
        #CONDOR - Saas only
        #FM_CONDOR_LUMBERJACK_HOST                        : "<FM_CONDOR_LUMBERJACK_HOST>"
        #FM_CONDOR_LUMBERJACK_PORT                        : "<FM_CONDOR_LUMBERJACK_PORT>"
        #FM_CONDOR_KEYSTORE                               : "<FM_CONDOR_KEYSTORE>"
        #FM_CONDOR_KEY_PASSWORD                           : "<FM_CONDOR_KEY_PASSWORD>"
        
    ports:
      - 8081:<FM_GENERAL_UI_PORT>
      - <FM_JVM_DEBUG_PORT>:<FM_JVM_DEBUG_PORT>
    depends_on:
      - fcmongo
    volumes:
     - "./mounts/resources:/opt/axway/FlowManager/resources"
     - "./mounts/plugins:/opt/axway/FlowManager/conf/schemas/storage/"
     - "./mounts/logs:/opt/axway/logs"
     - "./mounts/configs:/opt/axway/configs"
     - "./mounts/configs:/opt/axway/FlowManager/conf/license/"

  fcmongo:
    #build: ./mongo_3.6/
    image: fc-docker.lab.buch.axway.int/mft/mongo:3.6
    hostname: fcmongo
    ports:
      - 27017:27017
      - 27018:27018
    volumes:
       - "./mounts/mongo_data:/data/db/"
       - "./mounts/mongo_certificates:/certificates"
       - "./mounts/mongo_config:/configs"
    environment:
      MONGODB_ADMIN_USER              : root
      MONGODB_ADMIN_PASS              : storage
      MONGODB_APPLICATION_DATABASE    : umcft
      MONGODB_APPLICATION_USER        : storage
      MONGODB_APPLICATION_PASS        : storage
      MONGODB_PORT                    : "27018"
      MONGODB_USE_SSL                 : "false"
      MONGODB_ROOT_CA                 : "rootCA.pem"
      MONGODB_CERTIFICATE             : "mongodb.pem"
      
