version: '3.4'
services:
  flowmanager1:
    extends:
      service: flowmanager
      file: ./docker-compose-template.yml
    environment:
      FM_GENERAL_FQDN: "flowmanager1"
      FM_GENERAL_HOSTNAME: "flowmanager1"
      FM_GENERAL_UI_PORT: "8081"
    ports:
      - "8081:8081"


  flowmanager2:
    extends:
      service: flowmanager
      file: ./docker-compose-template.yml
    environment:
      FM_GENERAL_FQDN: "flowmanager2"
      FM_GENERAL_HOSTNAME: "flowmanager2"
      FM_GENERAL_UI_PORT: "8082"
    ports:
      - "8082:8082"

  fcmongo:
    #build: ./mongo_3.6/
    image: fc-docker.lab.buch.axway.int/mft/mongo:3.6
    hostname: fcmongo
    ports:
      - 27017:27017
      - 27018:27018
    volumes:
       - "./mounts/mongo_data:/data/db/"
       - "./mounts/mongo_certificates:/certificates"
       - "./mounts/mongo_config:/configs"
    environment:
      MONGODB_ADMIN_USER              : root
      MONGODB_ADMIN_PASS              : storage
      MONGODB_APPLICATION_DATABASE    : umcft
      MONGODB_APPLICATION_USER        : storage
      MONGODB_APPLICATION_PASS        : storage
      MONGODB_PORT                    : "27018"
      MONGODB_USE_SSL                 : "false"
      MONGODB_ROOT_CA                 : "rootCA.pem"
      MONGODB_CERTIFICATE             : "mongodb.pem"
  
  redis:
    image: redis
    container_name: redis
    expose:
      - 6379
    ports:
      - 6379:6379
