version: '3.4'
services:
  fchost:
    image: cgqajenkins.lab.buch.axway.int:8083/flowcentral-uma:latest
    stdin_open: true
    hostname: "fchost"
    tty: true
    expose: [8081]
    environment:
        ### EULA ###
        ACCEPT_EULA: "yes"

        ### General ###
        FQDN                      : "fchost"
        HOSTNAME                  : "fchost"
        GENERAL_ENCRYPTION_KEY    : "Secret01"
        GENERAL_LOGGING_LEVEL     : "INFO"

        ### APIC settings ###
        APIC_USE_CATALOG          : "true"
        APIC_PUBLICKEY            : "/opt/axway/configs/public_key.pem"
        APIC_PRIVATEKEY           : "/opt/axway/configs/private_key.pem"
        APIC_HOST                 : "https://apicentral.axway.com"
        APIC_CLIENTID             : "DOSA_977f7227974b4a959acadc8a40a3d229"
        APIC_TOKENURL             : "https://login.axway.com/auth/realms/Broker/protocol/openid-connect/token"

        ### Mongo ###
        MONGODB_HOST              : "fcmongo"
        MONGODB_PORT              : "27018"
        MONGODB_USER_NAME         : "storage"
        MONGODB_USER_PASSWORD     : "storage"

        #CFT
        CFT_SHARED_SECRET         : "Secret01"
        
        ### Business ###
        BUSINESS_CA_CERTIF_ALIAS  : "inter_bus"
        BUSINESS_CA_FILE          : "/opt/axway/configs/businessca.jks"
        BUSINESS_CA_PASSWORD      : "Secret01"

        ### Governance ###
        GOVERNANCE_CA_CERTIF_ALIAS: "passportcaproduct"
        GOVERNANCE_CA_FILE        : "/opt/axway/configs/governanceca.jks"
        GOVERNANCE_CA_PASSWORD    : "Secret01"

        ### Certificates ###
        HTTPS_USE_CUSTOM_CERT     : "true"
        HTTPS_CERT_ALIAS          : "apicertificate"
        HTTPS_KEYSTORE            : "/opt/axway/configs/uicert.jks"
        HTTPS_KEYSTORE_PASSWORD   : "Secret01"
        CERTIFICATE_EXPIRATION_NOTIFICATION: "60"
    ports:
      - 8081:8081
    depends_on:
      - fcmongo
    volumes:
     - "./mounts/fc_logs:/opt/axway/fc_logs"
     - "./mounts/fc_keys:/opt/axway/FlowCentral/data/keys/com.axway.nodes.ume"
     - "./mounts/configs:/opt/axway/configs"
     - "./mounts/configs:/opt/axway/FlowCentral/conf/license/"

  fcmongo:
    build: ./mongo-3.4/ 
    expose:
      - 27018
    volumes:
      - "./mounts/mongo_data:/data/db/"
    ports:
      - 27018:27018
    environment:
      MONGODB_ADMIN_USER              : root
      MONGODB_ADMIN_PASS              : storage
      MONGODB_APPLICATION_DATABASE    : umcft
      MONGODB_APPLICATION_USER        : storage
      MONGODB_APPLICATION_PASS        : storage