version: '3.4'
services:
  flowcentral:
    image: <IMAGE_NAME>:<IMAGE_TAG>
    stdin_open: true
    hostname: "<FM_GENERAL_HOSTNAME>"
    tty: true
    environment:
        ### EULA ###
        ACCEPT_EULA: "<ACCEPT_EULA>"
        
        #General
        FM_GENERAL_FQDN                              : "<FM_GENERAL_FQDN>"
        FM_GENERAL_HOSTNAME                          : "<FM_GENERAL_HOSTNAME>"
        FM_GENERAL_UI_PORT                           : "<FM_GENERAL_UI_PORT>"
        FM_GENERAL_SAAS_MODE                         : "<FM_GENERAL_SAAS_MODE>"
        FM_GENERAL_HTTP_PORT                         : "<FM_GENERAL_HTTP_PORT>"
        FM_GENERAL_ENCRYPTION_KEY                    : "<FM_GENERAL_ENCRYPTION_KEY>"
        FM_GENERAL_LOGGING_LEVEL                     : "<FM_GENERAL_LOGGING_LEVEL>"
        FM_GENERAL_LICENSE                           : "<FM_GENERAL_LICENSE>"
        FM_GENERAL_CUSTOM_LOCATION_PATH              : "<FM_GENERAL_CUSTOM_LOCATION_PATH>"
        FM_LOGS_CONSOLE                              : "<FM_LOGS_CONSOLE>"

        #METRICS
        FM_METRICS_ENABLED                           : "<FM_METRICS_ENABLED>"     

        #HTTPS
        FM_HTTPS_USE_CUSTOM_CERT                     : "<FM_HTTPS_USE_CUSTOM_CERT>"
        FM_HTTPS_KEYSTORE                            : "<FM_HTTPS_KEYSTORE>"
        FM_HTTPS_CERT_ALIAS                          : "<FM_HTTPS_CERT_ALIAS>"
        FM_HTTPS_KEYSTORE_PASSWORD                   : "<FM_HTTPS_KEYSTORE_PASSWORD>"
        FM_SESSION_IDLE                              : "<FM_SESSION_IDLE>"
        FM_SESSION_EXPIRATION                        : "<FM_SESSION_EXPIRATION>"
        
        #Platform
        FM_PLATFORM_HOST                             : "<FM_PLATFORM_HOST>"
        
        #Redis
        FM_REDIS_ENABLED                             : "<FM_REDIS_ENABLED>"
        FM_REDIS_HOSTNAME                            : "<FM_REDIS_HOSTNAME>"
        FM_REDIS_PORT                                : "<FM_REDIS_PORT>"


        #CFT
        FM_CFT_SHARED_SECRET                         : "<FM_CFT_SHARED_SECRET>"
        FM_CFT_SFTP_ENABLED                          : "<FM_CFT_SFTP_ENABLED>"
        
        #ST
        FM_ST_WHITELISTING_ENABLED                   : "<FM_ST_WHITELISTING_ENABLED>"
        FM_ST_WHITELISTING_WATCHDOG_DELAY            : "<FM_ST_WHITELISTING_WATCHDOG_DELAY>"
        
        #APIC
        FM_APIC_USE_CATALOG                          : "<FM_APIC_USE_CATALOG>"
        FM_APIC_HOST                                 : "<FM_APIC_HOST>"
        FM_APIC_CLIENTID                             : "<FM_APIC_CLIENTID>"
        FM_APIC_PUBLICKEY                            : "<FM_APIC_PUBLICKEY>"
        FM_APIC_PRIVATEKEY                           : "<FM_APIC_PRIVATEKEY>"
        FM_APIC_TOKENURL                             : "<FM_APIC_TOKENURL>"
        
        #Mongo
        FM_DATABASE_HOST                             : "<FM_DATABASE_HOST>"
        FM_DATABASE_PORT                             : "<FM_DATABASE_PORT>"
        FM_DATABASE_USER_NAME                        : "<FM_DATABASE_USER_NAME>"
        FM_DATABASE_USER_PASSWORD                    : "<FM_DATABASE_USER_PASSWORD>"
        FM_DATABASE_USE_SSL                          : "<FM_DATABASE_USE_SSL>"
        FM_DATABASE_CERTIFICATES                     : "<FM_DATABASE_CERTIFICATES>"
        FM_DISABLE_CHECK_REACHABLE_HOST              : "<FM_DISABLE_CHECK_REACHABLE_HOST>"

        #Business
        FM_BUSINESS_CA_CERTIF_ALIAS                  : "<FM_BUSINESS_CA_CERTIF_ALIAS>"
        FM_BUSINESS_CA_FILE                          : "<FM_BUSINESS_CA_FILE>"
        FM_BUSINESS_CA_PASSWORD                      : "<FM_BUSINESS_CA_PASSWORD>"

        #GOVERNANCE
        FM_GOVERNANCE_CA_CERTIF_ALIAS                : "<FM_GOVERNANCE_CA_CERTIF_ALIAS>"
        FM_GOVERNANCE_CA_FILE                        : "<FM_GOVERNANCE_CA_FILE>"
        FM_GOVERNANCE_CA_PASSWORD                    : "<FM_GOVERNANCE_CA_PASSWORD>"
        
        #JVM
        FM_JVM_XMX                                   : "<FM_JVM_XMX>"
        FM_JVM_XMS                                   : "<FM_JVM_XMS>"
        FM_JVM_XMN                                   : "<FM_JVM_XMN>"
        FM_JVM_DEBUG_ENABLED                         : "<FM_JVM_DEBUG_ENABLED>"
        FM_JVM_DEBUG_PORT                            : "<FM_JVM_DEBUG_PORT>"
        FM_JVM_DEBUG_SUSPEND                         : "<FM_JVM_DEBUG_SUSPEND>"
        FM_JVM_CUSTOM_ARGS                           : "<FM_JVM_CUSTOM_ARGS>"
        
        #EXTERNAL
        FM_EXTERNAL_FQDN                             : "<FM_EXTERNAL_FQDN>"              
        FM_EXTERNAL_UI_PORT                          : "<FM_EXTERNAL_UI_PORT>"                            

        #Sentinel 
        FM_SENTINEL_AUDIT_ENABLED                     : "<FM_SENTINEL_AUDIT_ENABLED>"
        FM_SENTINEL_FRONT_END_HOST                    : "<FM_SENTINEL_FRONT_END_HOST>"
        FM_SENTINEL_FRONT_END_PORT                    : "<FM_SENTINEL_FRONT_END_PORT>"
        FM_SENTINEL_FRONT_END_SSL_PORT                : "<FM_SENTINEL_FRONT_END_SSL_PORT>"
        FM_SENTINEL_UI_HOST                           : "<FM_SENTINEL_UI_HOST>"
        FM_SENTINEL_UI_PORT                           : "<FM_SENTINEL_UI_PORT>"
        FM_SENTINEL_USE_CG_CA                         : "<FM_SENTINEL_USE_CG_CA>"
        
        #ARS
        FM_ARS_HTTPONLY                               : "<FM_ARS_HTTPONLY>"
        
        # Proxy for SaaS Mode
        FM_PROXY_ENABLED                              : "<FM_PROXY_ENABLED>"
        FM_PROXY_HOST                                 : "<FM_PROXY_HOST>"
        FM_PROXY_PORT                                 : "<FM_PROXY_PORT>"

        #CONDOR
        #FM_CONDOR_LUMBERJACK_HOST                        : "<FM_CONDOR_LUMBERJACK_HOST>"
        #FM_CONDOR_LUMBERJACK_PORT                        : "<FM_CONDOR_LUMBERJACK_PORT>"
        #FM_CONDOR_KEYSTORE                               : "<FM_CONDOR_KEYSTORE>"
        #FM_CONDOR_KEY_PASSWORD                           : "<FM_CONDOR_KEY_PASSWORD>"

        
    ports:
      - <FM_EXTERNAL_UI_PORT>:<FM_EXTERNAL_UI_PORT>
      - <FM_JVM_DEBUG_PORT>:<FM_JVM_DEBUG_PORT>
    depends_on:
      - fcmongo
    volumes:
     - "./mounts/resources:/opt/axway/FlowManager/resources"
     - "./mounts/plugins:/opt/axway/FlowManager/conf/schemas/storage/"
     - "./mounts/logs:/opt/axway/logs"
     - "./mounts/configs:/opt/axway/configs"
     - "./mounts/configs:/opt/axway/FlowManager/conf/license/"

  fcmongo:
    #build: ./mongo_3.6/
    image: fc-docker.lab.buch.axway.int/mft/mongo:3.6
    hostname: fcmongo
    ports:
      - 27017:27017
      - 27018:27018
    volumes:
       - "./mounts/mongo_data:/data/db/"
       - "./mounts/mongo_certificates:/certificates"
       - "./mounts/mongo_config:/configs"
    environment:
      MONGODB_ADMIN_USER              : root
      MONGODB_ADMIN_PASS              : storage
      MONGODB_APPLICATION_DATABASE    : umcft
      MONGODB_APPLICATION_USER        : storage
      MONGODB_APPLICATION_PASS        : storage
      MONGODB_PORT                    : "27018"
      MONGODB_USE_SSL                 : "false"
      MONGODB_ROOT_CA                 : "rootCA.pem"
      MONGODB_CERTIFICATE             : "mongodb.pem"
      
