version: '3.4'
services:
  flowcentral:
    image: fc-docker.lab.buch.axway.int/mft/flowcentral_dev:latest
    stdin_open: true
    hostname: "flowcentral"
    tty: true
    environment:
        ### EULA ###
        ACCEPT_EULA: "yes"
        
        #General
        FC_GENERAL_FQDN                              : "flowcentral"
        FC_GENERAL_HOSTNAME                          : "flowcentral"
        FC_GENERAL_UI_PORT                           : "8081"
        FC_GENERAL_SAAS_MODE                         : "false"
        FC_GENERAL_HTTP_PORT                         : ""
        FC_GENERAL_ENCRYPTION_KEY                    : "Secret01"
        FC_GENERAL_LOGGING_LEVEL                     : "INFO"
        FC_GENERAL_LICENSE                           : "license.xml"
        FC_GENERAL_CUSTOM_LOCATION_PATH              : "/opt/axway/fc_logs"
        FC_LOGS_CONSOLE                              : "yes"

        #HTTPS
        FC_HTTPS_USE_CUSTOM_CERT                     : "true"
        FC_HTTPS_KEYSTORE                            : "/opt/axway/configs/uicert.jks"
        FC_HTTPS_CERT_ALIAS                          : "uicert"
        FC_HTTPS_KEYSTORE_PASSWORD                   : "Secret01"
        FC_SESSION_IDLE                              : "900"
        FC_SESSION_EXPIRATION                        : "28800"
        
        #Platform
        FC_PLATFORM_HOST                             : "platform.axwaytest.net"
        FC_PLATFORM_PORT                             : "443"
        
        #Redis
        FC_REDIS_ENABLED                             : "true"
        FC_REDIS_HOSTNAME                            : "redis"
        FC_REDIS_PORT                                : "6379"


        #CFT
        FC_CFT_SHARED_SECRET                         : "Secret01"
        FC_CFT_SFTP_ENABLED                          : "false"
        
        #ST
        FC_ST_WHITELISTING_ENABLED                   : "false"
        FC_ST_WHITELISTING_WATCHDOG_DELAY            : "120"
        
        #APIC
        FC_APIC_USE_CATALOG                          : "true"
        FC_APIC_HOST                                 : "https://apicentral.axway.com"
        FC_APIC_CLIENTID                             : "DOSA_3c4ebd8cc4254c69a63ba3c0930ffe5b"
        FC_APIC_PUBLICKEY                            : "/opt/axway/configs/public_key.pem"
        FC_APIC_PRIVATEKEY                           : "/opt/axway/configs/private_key.pem"
        
        #Mongo
        FC_DATABASE_HOST                             : "fcmongo"
        FC_DATABASE_PORT                             : "27018"
        FC_DATABASE_USER_NAME                        : "storage"
        FC_DATABASE_USER_PASSWORD                    : "storage"
        FC_DATABASE_USE_SSL                          : "false"
        FC_DATABASE_CERTIFICATES                     : "/opt/axway/configs/truststore.jks"
        FC_DISABLE_CHECK_REACHABLE_HOST              : "false"

        #Business
        FC_BUSINESS_CA_CERTIF_ALIAS                  : "inter_bus"
        FC_BUSINESS_CA_FILE                          : "/opt/axway/configs/businessca.jks"
        FC_BUSINESS_CA_PASSWORD                      : "Secret01"

        #GOVERNANCE
        FC_GOVERNANCE_CA_CERTIF_ALIAS                : "govinter_fc"
        FC_GOVERNANCE_CA_FILE                        : "/opt/axway/configs/governanceca.jks"
        FC_GOVERNANCE_CA_PASSWORD                    : "Secret01"
        
        #JVM
        FC_JVM_XMX                                   : "2G"
        FC_JVM_XMS                                   : "512M"
        FC_JVM_XMN                                   : "768M"
        FC_JVM_DEBUG_ENABLED                         : "false"
        FC_JVM_DEBUG_PORT                            : "8000"
        FC_JVM_DEBUG_SUSPEND                         : "false"
        #FC_JVM_CUSTOM_ARGS                          : "IF NEEDED"
        
        #EXTERNAL
        #FC_EXTERNAL_FQDN                             : "kube-cg-master.lab.buch.axway.int"              
        #FC_EXTERNAL_UI_PORT                          : "31617"                            

        #Sentinel 
        FC_SENTINEL_AUDIT_ENABLED                     : "false"
        FC_SENTINEL_FRONT_END_HOST                    : "localhost"
        FC_SENTINEL_FRONT_END_PORT                    : "1305"
        FC_SENTINEL_FRONT_END_SSL_PORT                : "1303"
        FC_SENTINEL_UI_HOST                           : "localhost"
        FC_SENTINEL_UI_PORT                           : "1309"
        FC_SENTINEL_USE_CG_CA                         : "true"
        
        #ARS
        FC_ARS_HTTPONLY                               : "true"  # this will activate http only if saas_mode is active
        
        # Proxy for SaaS Mode
        FC_PROXY_ENABLED                              : "true"
        FC_PROXY_HOST                                 : "flowcentral-bridge.axwaytest.net"
        FC_PROXY_PORT                                 : "8444"

        
    ports:
      - 8081:8081
    depends_on:
      - fcmongo
    volumes:
     - "./mounts/fc_resources:/opt/axway/FlowCentral/resources"
     - "./mounts/fc_plugins:/opt/axway/FlowCentral/conf/schemas/storage/"
     - "./mounts/fc_logs:/opt/axway/fc_logs"
     - "./mounts/configs:/opt/axway/configs"
     - "./mounts/configs:/opt/axway/FlowCentral/conf/license/"

  fcmongo:
    #build: ./mongo_3.6/
    image: fc-docker.lab.buch.axway.int/mft/mongo:3.6
    hostname: fcmongo
    volumes:
       - "./mounts/mongo_data:/data/db/"
       - "./mounts/mongo_certificates:/certificates"
       - "./mounts/mongo_config:/configs"
    environment:
      MONGODB_ADMIN_USER              : root
      MONGODB_ADMIN_PASS              : storage
      MONGODB_APPLICATION_DATABASE    : umcft
      MONGODB_APPLICATION_USER        : storage
      MONGODB_APPLICATION_PASS        : storage
      MONGODB_PORT                    : "27018"
      MONGODB_USE_SSL                 : "false"
      MONGODB_ROOT_CA                 : "rootCA.pem"
      MONGODB_CERTIFICATE             : "mongodb.pem"
      
  redis:
    image: redis
    container_name: redis
    expose:
      - 6379
