version: '3.4'
services:
  flowcentral:
    image: fc-docker.lab.buch.axway.int/mft/flowcentral_dev:latest 
    stdin_open: true
    hostname: "flowcentral"
    tty: true
    environment:
        ### EULA ###
        ACCEPT_EULA: "yes"
        
        #General
        FM_GENERAL_FQDN                              : "flowcentral"
        FM_GENERAL_HOSTNAME                          : "flowcentral"
        FM_GENERAL_UI_PORT                           : "8081"
        FM_GENERAL_SAAS_MODE                         : "false"
        FM_GENERAL_HTTP_PORT                         : ""
        FM_GENERAL_ENCRYPTION_KEY                    : "Secret01"
        FM_GENERAL_LOGGING_LEVEL                     : "INFO"
        FM_GENERAL_LICENSE                           : "license.xml"
        FM_GENERAL_CUSTOM_LOCATION_PATH              : "/opt/axway/FM_logs"
        FM_LOGS_CONSOLE                              : "yes"
        FM_METRICS_ENABLED                           : "true"     

        #HTTPS
        FM_HTTPS_USE_CUSTOM_CERT                     : "true"
        FM_HTTPS_KEYSTORE                            : "/opt/axway/configs/uicert.jks"
        FM_HTTPS_CERT_ALIAS                          : "uicert"
        FM_HTTPS_KEYSTORE_PASSWORD                   : "Secret01"
        FM_SESSION_IDLE                              : "900"
        FM_SESSION_EXPIRATION                        : "28800"
        
        #Platform
        FM_PLATFORM_HOST                             : "platform.axwaytest.net"
        
        #Redis
        FM_REDIS_ENABLED                             : "true"
        FM_REDIS_HOSTNAME                            : "redis"
        FM_REDIS_PORT                                : "6379"


        #CFT
        FM_CFT_SHARED_SECRET                         : "Secret01"
        FM_CFT_SFTP_ENABLED                          : "false"
        
        #ST
        FM_ST_WHITELISTING_ENABLED                   : "false"
        FM_ST_WHITELISTING_WATCHDOG_DELAY            : "120"
        
        #APIC
        FM_APIC_USE_CATALOG                          : "true"
        FM_APIC_HOST                                 : "https://apicentral.axway.com"
        FM_APIC_CLIENTID                             : "DOSA_3c4ebd8cc4254c69a63ba3c0930ffe5b"
        FM_APIC_PUBLICKEY                            : "/opt/axway/configs/public_key.pem"
        FM_APIC_PRIVATEKEY                           : "/opt/axway/configs/private_key.pem"
        
        #Mongo
        FM_DATABASE_HOST                             : "fcmongo"
        FM_DATABASE_PORT                             : "27018"
        FM_DATABASE_USER_NAME                        : "storage"
        FM_DATABASE_USER_PASSWORD                    : "storage"
        FM_DATABASE_USE_SSL                          : "false"
        FM_DATABASE_CERTIFICATES                     : "/opt/axway/configs/truststore.jks"
        FM_DISABLE_CHECK_REACHABLE_HOST              : "false"

        #Business
        FM_BUSINESS_CA_CERTIF_ALIAS                  : "ibusca1"
        FM_BUSINESS_CA_FILE                          : "/opt/axway/configs/businessca.jks"
        FM_BUSINESS_CA_PASSWORD                      : "Secret01"

        #GOVERNANCE
        FM_GOVERNANCE_CA_CERTIF_ALIAS                : "govinter_fc"
        FM_GOVERNANCE_CA_FILE                        : "/opt/axway/configs/governanceca.jks"
        FM_GOVERNANCE_CA_PASSWORD                    : "Secret01"
        
        #JVM
        FM_JVM_XMX                                   : "2G"
        FM_JVM_XMS                                   : "512M"
        FM_JVM_XMN                                   : "768M"
        FM_JVM_DEBUG_ENABLED                         : "false"
        FM_JVM_DEBUG_PORT                            : "8000"
        FM_JVM_DEBUG_SUSPEND                         : "false"
        #FM_JVM_CUSTOM_ARGS                          : "IF NEEDED"
        
        #EXTERNAL
        #FM_EXTERNAL_FQDN                             : "kube-cg-master.lab.buch.axway.int"              
        #FM_EXTERNAL_UI_PORT                          : "31617"                            

        #Sentinel 
        FM_SENTINEL_AUDIT_ENABLED                     : "false"
        FM_SENTINEL_FRONT_END_HOST                    : "localhost"
        FM_SENTINEL_FRONT_END_PORT                    : "1305"
        FM_SENTINEL_FRONT_END_SSL_PORT                : "1303"
        FM_SENTINEL_UI_HOST                           : "localhost"
        FM_SENTINEL_UI_PORT                           : "1309"
        FM_SENTINEL_USE_CG_CA                         : "true"
        
        #ARS
        FM_ARS_HTTPONLY                               : "true"  # this will activate http only if saas_mode is active
        
        # Proxy for SaaS Mode
        FM_PROXY_ENABLED                              : "true"
        FM_PROXY_HOST                                 : "flowcentral-bridge.axwaytest.net"
        FM_PROXY_PORT                                 : "8444"

        
    ports:
      - 8081:8081
    depends_on:
      - fcmongo
    volumes:
     - "./mounts/resources:/opt/axway/FlowManager/resources"
     - "./mounts/plugins:/opt/axway/FlowManager/conf/schemas/storage/"
     - "./mounts/logs:/opt/axway/logs"
     - "./mounts/configs:/opt/axway/configs"
     - "./mounts/configs:/opt/axway/FlowManager/conf/license/"

  fcmongo:
    #build: ./mongo_3.6/
    image: fc-docker.lab.buch.axway.int/mft/mongo:3.6
    hostname: fcmongo
    volumes:
       - "./mounts/mongo_data:/data/db/"
       - "./mounts/mongo_certificates:/certificates"
       - "./mounts/mongo_config:/configs"
    environment:
      MONGODB_ADMIN_USER              : root
      MONGODB_ADMIN_PASS              : storage
      MONGODB_APPLICATION_DATABASE    : umcft
      MONGODB_APPLICATION_USER        : storage
      MONGODB_APPLICATION_PASS        : storage
      MONGODB_PORT                    : "27018"
      MONGODB_USE_SSL                 : "false"
      MONGODB_ROOT_CA                 : "rootCA.pem"
      MONGODB_CERTIFICATE             : "mongodb.pem"
      
