version: '3.4'
services:
  flowcentral:
    image: cgqajenkins.lab.buch.axway.int:8083/flowcentral-openjdk:latest
    stdin_open: true
    hostname: "flowcentral"
    tty: true
    environment:
        ### EULA ###
        ACCEPT_EULA: "yes"
        
        #General
        FC_GENERAL_FQDN                              : "flowcentral"
        FC_GENERAL_HOSTNAME                          : "flowcentral"
        FC_GENERAL_UI_PORT                           : "8081"
        FC_GENERAL_ENCRYPTION_KEY                    : "Secret01"
        FC_GENERAL_LOGGING_LEVEL                     : "INFO"
        FC_GENERAL_LICENSE                           : "license.xml"
        FC_GENERAL_CUSTOM_LOCATION_PATH              : "/opt/axway/FlowCentral/logs"
        FC_LOGS_CONSOLE                              : "yes"

        #HTTPS
        FC_HTTPS_USE_CUSTOM_CERT                     : "true"
        FC_HTTPS_KEYSTORE                            : "/opt/axway/configs/uicert.jks"
        FC_HTTPS_CERT_ALIAS                          : "apicertificate"
        FC_HTTPS_KEYSTORE_PASSWORD                   : "Secret01"


        #CFT
        FC_CFT_SHARED_SECRET                         : "Secret01"

        #APIC
        FC_APIC_USE_CATALOG                          : "true"
        FC_APIC_HOST                                 : "https://apicentral.axway.com"
        FC_APIC_CLIENTID                             : "DOSA_3c4ebd8cc4254c69a63ba3c0930ffe5b"
        FC_APIC_PUBLICKEY                            : "/opt/axway/configs/public_key.pem"
        FC_APIC_PRIVATEKEY                           : "/opt/axway/configs/private_key.pem"
        
        #Mongo
        FC_MONGODB_HOST                              : "fcmongo"
        FC_MONGODB_PORT                              : "27018"
        FC_MONGODB_USER_NAME                         : "storage"
        FC_MONGODB_USER_PASSWORD                     : "storage"
        FC_MONGODB_USE_SSL                           : "false"
        MONGODB_TRUSTSTORE_FILE                   : "/opt/axway/configs/truststore.jks"
        FC_DISABLE_CHECK_REACHABLE_HOST              : "false"

        #Business
        FC_BUSINESS_CA_CERTIF_ALIAS                  : "inter_bus"
        FC_BUSINESS_CA_FILE                          : "/opt/axway/configs/businessca.jks"
        FC_BUSINESS_CA_PASSWORD                      : "Secret01"

        #GOVERNANCE
        FC_GOVERNANCE_CA_CERTIF_ALIAS                : "passportcaproduct"
        FC_GOVERNANCE_CA_FILE                        : "/opt/axway/configs/governanceca.jks"
        FC_GOVERNANCE_CA_PASSWORD                    : "Secret01"
        
        #JVM
        FC_JVM_XMX                                   : "2G"
        FC_JVM_XMS                                   : "512M"
        FC_JVM_XMN                                   : "768M"
        FC_JVM_DEBUG_ENABLED                         : "false"
        FC_JVM_DEBUG_PORT                            : "8000"
        FC_JVM_DEBUG_SUPSEND                         : "true"
        #FC_JVM_CUSTOM_ARGS                          : "IF NEEDED"
        
        #EXTERNAL
        FC_EXTERNAL_FQDN                             : "kube-cg-master.lab.buch.axway.int"                      
        FC_EXTERNAL_UI_PORT                          : "31617"

        
    ports:
      - 8081:8081
    depends_on:
      - fcmongo
    volumes:
     #- "./mounts/fc_logs:/opt/axway/fc_logs"
     - "./mounts/fc_keys:/opt/axway/FlowCentral/data/keys/com.axway.nodes.ume"
     - "./mounts/configs:/opt/axway/configs"
     - "./mounts/configs:/opt/axway/FlowCentral/conf/license/"

  fcmongo:
    build: ./mongo-3.4/ 
    volumes:
       - "./mounts/mongo_data:/data/db/"
    environment:
      MONGODB_ADMIN_USER              : root
      MONGODB_ADMIN_PASS              : storage
      MONGODB_APPLICATION_DATABASE    : umcft
      MONGODB_APPLICATION_USER        : storage
      MONGODB_APPLICATION_PASS        : storage

  cft-332:
    image: cgqajenkins.lab.buch.axway.int:8083/docker-cft:3.3.2
    hostname: "cft-332"
    environment:
      FC_HOST:                "flowcentral"
      FC_PORT:                "8081"
      FC_SHARED_SECRET:       "Secret01"
      FC_PERIODICITY:         "30"
      CFT_CG_HOST:            "flowcentral"
      CFT_CG_PORT:            "8081"
      CFT_CG_SHARED_SECRET:   "Secret01"
      CFT_CG_PERIODICITY:     "30"
      CFT_HOST:               "cft-332"
      CFT_PORT:               "8093"
      CFT_GROUP:              "Production.Linux"
      CFT_KEY:                "cat /run/secrets/cft-license"
      CFT_POLICY:             ""
      CFT_PESIT_PORT:         "17611"
      CFT_PESITSSL_PORT:      "18092"
      CFT_FQDN:               "cft-332"
      CFT_INSTANCE_ID:        "cft-332"
      CFT_INSTANCE_GROUP:     "dev.docker"
      CFT_CATALOG_SIZE:       "1000"
      CFT_COM_SIZE:           "1000"
      CFT_COMS_PORT:          "17651"
      CFT_COPILOT_PORT:       "17661"
      CFT_COPILOT_CG_PORT:    "17671"
      CFT_RESTAPI_PORT:       "17681"
      CFT_CG_ENABLE:          "YES"
      CFT_CG_POLICY:          ""
      CFT_JVM:                "1024"
      CFT_CFTDIRRUNTIME:      "/opt/axway/cft/runtime"
    ports:
      - "17611:17611"
      - "17621:17621"
      - "17651:17651"
      - "17661:17661"
      - "17671:17671"
      - "17681:17681"
      - "18092:18092"
    secrets:
      - cft-license
    depends_on:
      - flowcentral

  cft-34:
    image: cgqajenkins.lab.buch.axway.int:8083/docker-cft:3.4 
    hostname: "docker-cft-34"
    environment:
      FC_HOST:                "flowcentral"
      FC_PORT:                "8081"
      FC_SHARED_SECRET:       "Secret01"
      FC_PERIODICITY:         "30"
      CFT_CG_HOST:            "flowcentral"
      CFT_CG_PORT:            "8081"
      CFT_CG_SHARED_SECRET:   "Secret01"
      CFT_CG_PERIODICITY:     "30"
      CFT_HOST:               "docker-cft-34"
      CFT_PORT:               "8093"
      CFT_GROUP:              "Production.Linux"
      CFT_KEY:                "cat /run/secrets/cft-license"
      CFT_POLICY:             ""
      CFT_PESIT_PORT:         "1761"
      CFT_PESITSSL_PORT:      "18092"
      CFT_FQDN:               "cft-34"
      CFT_INSTANCE_ID:        "cft-34"
      CFT_INSTANCE_GROUP:     "docker"
      CFT_CATALOG_SIZE:       "1000"
      CFT_COM_SIZE:           "1000"
      CFT_COMS_PORT:          "1765"
      CFT_COPILOT_PORT:       "1766"
      CFT_COPILOT_CG_PORT:    "1767"
      CFT_RESTAPI_PORT:       "1768"
      CFT_CG_ENABLE:          "YES"
      CFT_CG_POLICY:          ""
      CFT_JVM:                "1024"
      CFT_CFTDIRRUNTIME:      "/opt/axway/cft/runtime"
    ports:
      - "1761:1761"
      - "1762:1762"
      - "1765:1765"
      - "1766:1766"
      - "1767:1767"
      - "1768:1768"
      - "8092:8092"
    secrets:
      - cft-license
    depends_on:
      - flowcentral

secrets:
  cft-license:
    file: ./licenses/cft.key