version: '3.4'
services:
  flowmanager:
    image: fc-docker.lab.buch.axway.int/mft/flowcentral_dev:latest 
    stdin_open: true
    hostname: "flowmanager"
    tty: true
    environment:
        ### EULA ###
        ACCEPT_EULA: "yes"
        
        #General
        FM_GENERAL_FQDN                              : "<FQDN>"
        FM_GENERAL_UI_PORT                           : "8081"
        FM_GENERAL_ENCRYPTION_KEY                    : "Secret01"
        FM_GENERAL_LOGGING_LEVEL                     : "INFO"
        #FM_GENERAL_LICENSE                           : "license.xml"
        FM_LOGS_CONSOLE                              : "yes"
        #FM_GENERAL_CUSTOM_LOCATION_PATH              : "/opt/axway/FM_logs"
        FM_METRICS_ENABLED                           : "true" 
       
        #HTTPS
        FM_HTTPS_USE_CUSTOM_CERT                     : "true"
        FM_HTTPS_KEYSTORE                            : "/opt/axway/configs/uicert.jks"
        FM_HTTPS_CERT_ALIAS                          : "uicert"
        FM_HTTPS_KEYSTORE_PASSWORD                   : "Secret01"
       
        #Redis
        FM_REDIS_ENABLED                             : "false"
        FM_REDIS_HOSTNAME                            : "redis"
        FM_REDIS_PORT                                : "6379"
        #FM_REDIS_AUTH_ENABLED                        : "false"
        #FM_REDIS_PASSWORD                            : "<FM_REDIS_PASSWORD>"
        #optional,only for redis 6.x, it should be empty if not used
        #FM_REDIS_USER                                : "<FM_REDIS_USER>"
        #FM_REDIS_SSL_ENABLED                         : "<FM_REDIS_SSL_ENABLED>"
        #optional, it should be empty if redis ca is not set 
        #FM_REDIS_SSL_CA                              : "<FM_REDIS_SSL_CA>"

        #CFT
        FM_CFT_SHARED_SECRET                         : "Secret01"
        
        #APIC
        FM_APIC_USE_CATALOG                          : "true"
        FM_APIC_HOST                                 : "https://apicentral.axway.com"
        FM_APIC_CLIENTID                             : "DOSA_3c4ebd8cc4254c69a63ba3c0930ffe5b"
        FM_APIC_PUBLICKEY                            : "/opt/axway/configs/public_key.pem"
        FM_APIC_PRIVATEKEY                           : "/opt/axway/configs/private_key.pem"
        
        #Mongo
        FM_DATABASE_HOST                             : "fcmongo"
        FM_DATABASE_PORT                             : "27018"
        FM_DATABASE_NAME                             : "umcft"
        FM_DATABASE_USER_NAME                        : "storage"
        FM_DATABASE_USER_PASSWORD                    : "storage"
        FM_DATABASE_USE_SSL                          : "false"
        FM_DATABASE_CERTIFICATES                     : "/opt/axway/configs/truststore.jks"

        #GOVERNANCE
        FM_GOVERNANCE_CA_CERTIF_ALIAS                : "govinter_fc"
        FM_GOVERNANCE_CA_FILE                        : "/opt/axway/configs/governanceca.jks"
        FM_GOVERNANCE_CA_PASSWORD                    : "Secret01"
        
        #JVM
        FM_JVM_XMX                                   : "2G"
        FM_JVM_XMS                                   : "512M"
        FM_JVM_XMN                                   : "768M"
        FM_JVM_DEBUG_ENABLED                         : "false"
        FM_JVM_DEBUG_PORT                            : "8000"
        FM_JVM_DEBUG_SUSPEND                         : "false"

        #Sentinel 
        FM_SENTINEL_AUDIT_ENABLED                     : "false"
        FM_SENTINEL_FRONT_END_HOST                    : "localhost"
        FM_SENTINEL_FRONT_END_PORT                    : "1305"
        FM_SENTINEL_FRONT_END_SSL_PORT                : "1303"
        
    ports:
      - 8081:8081
    depends_on:
      - fcmongo
    volumes:
     - "./mounts/resources:/opt/axway/FlowManager/resources"
     - "./mounts/plugins:/opt/axway/FlowManager/conf/schemas/storage/"
     - "./mounts/logs:/opt/axway/logs"
     - "./mounts/configs:/opt/axway/configs"
     - "./mounts/configs:/opt/axway/FlowManager/conf/license/"

  fcmongo:
    #build: ./mongo_3.6/
    image: fc-docker.lab.buch.axway.int/mft/mongo:3.6
    hostname: fcmongo
    volumes:
       - "./mounts/mongo_data:/data/db/"
       - "./mounts/mongo_certificates:/certificates"
       - "./mounts/mongo_config:/configs"
    environment:
      MONGODB_ADMIN_USER              : root
      MONGODB_ADMIN_PASS              : storage
      MONGODB_APPLICATION_DATABASE    : umcft
      MONGODB_APPLICATION_USER        : storage
      MONGODB_APPLICATION_PASS        : storage
      MONGODB_PORT                    : "27018"
      MONGODB_USE_SSL                 : "false"
      MONGODB_ROOT_CA                 : "rootCA.pem"
      MONGODB_CERTIFICATE             : "mongodb.pem"
      
