---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flowmanager
  labels:
    app: flowmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flowmanager
  template:
    metadata:
      labels:
        app: flowmanager
    spec:
      serviceAccountName: flowmanager
      securityContext:
        fsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1001
      containers:
        - name: flowmanager
          image: ""
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: flowmanager-env
          env:
            - name: ACCEPT_EULA
              value: ""
            - name: FM_GENERAL_LOGGING_LEVEL
              value: "INFO"
            - name: FM_LOGS_CONSOLE
              value: "yes"
            - name: FM_GENERAL_FQDN
              value: "YOUR_HOST"  #The host representing the public accessible FM address
            - name: FM_GENERAL_UI_PORT
              value: "443"
            - name: FM_DATABASE_HOST
              value: "mongodb.flowmanager.svc.cluster.local"
            - name: FM_DATABASE_NAME
              value: "umcft"
            - name: FM_DATABASE_USE_SSL
              value: "false"
            - name: FM_DATABASE_CERTIFICATES
              value: ""
            - name: FM_REDIS_ENABLED
              value: "false"
            - name: FM_REDIS_HOSTNAME
              value: "redis.db.svc.cluster.local"
            - name: FM_REDIS_PORT
              value: "6379"
            - name: FM_REDIS_SSL_ENABLED
              value: "false"
            - name: FM_HTTPS_DISABLED
              value: "false"
            - name: FM_HTTPS_CERT_ALIAS
              value: "ui"
            - name: FM_HTTPS_USE_CUSTOM_CERT
              value: "false"
            - name: FM_HTTPS_KEYSTORE
              value: /opt/axway/FlowManager/configs/uicert.p12
            - name: FM_HTTPS_KEYSTORE_PASSWORD
              value: ""
            - name: FM_GOVERNANCE_CA_FILE
              value: /opt/axway/FlowManager/configs/governanceca.p12
            - name: FM_GOVERNANCE_CA_PASSWORD
              value: ""
            - name: FM_CFT_SHARED_SECRET
              value: ""
            - name: FM_CFT_UPDATES_PATH
              value: "/opt/axway/FlowManager/updates/cft/"
            - name: FM_JVM_XMN
              value: "768M"
            - name: FM_JVM_XMS
              value: "512M"
            - name: FM_JVM_XMX
              value: "2G"
          volumeMounts:
            - name: license
              readOnly: true
              mountPath: /opt/axway/FlowManager/conf/license/license.xml
              subPath: license.xml
            - name: uicert
              readOnly: true
              mountPath: /opt/axway/configs/uicert.p12
              subPath: uicert.p12
            - name: governance
              readOnly: true
              mountPath: /opt/axway/configs/governance.p12
              subPath: governance.p12
          ports:
            - name: fm-https
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            failureThreshold: 2
            httpGet:
              path: /api/v2/internals/stability
              port: 8081
              scheme: HTTPS
            initialDelaySeconds: 100
            periodSeconds: 10
            successThreshold: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /fm/login
              port: 8081
              scheme: HTTPS
            initialDelaySeconds: 100
            periodSeconds: 5
            successThreshold: 3
      volumes:
        - name: license
          secret:
            secretName: flowmanager-license
            defaultMode: 420
        - name: uicert
          secret:
            secretName: flowmanager-uicert
            defaultMode: 420
        - name: governance
          secret:
            secretName: flowmanager-governance
            defaultMode: 420
