---
apiVersion: v1
kind: Secret
metadata:
  name: flowmanager-env
  labels:
    app: flowmanager
type: Opaque
data:
  FM_GENERAL_ENCRYPTION_KEY: "U2VjcmV0MDE="
  FM_HTTPS_KEYSTORE_PASSWORD: "U2VjcmV0MDE="
  FM_CFT_SHARED_SECRET: "U2VjcmV0MDE="
  FM_DATABASE_USER_NAME: "YXBwX3VzZXI="
  FM_DATABASE_USER_PASSWORD: "YXBwX3Bhc3M="
  FM_GOVERNANCE_CA_PASSWORD: "U2VjcmV0MDE="
