version: '3.4'
services:
  fcmongo:
    image: cgqajenkins.lab.buch.axway.int:8083/flowcentral-mongo:3.6
    hostname: fcmongo #THE HOSTNAME MUST MATCH THE ONE SPECIFIED IN YOUR MONGODB CERTIFICATE
    volumes:
       - "./mounts/mongo_data:/data/db/"
       - "./mounts/mongo_certificates:/certificates"
       - "./mounts/mongo_config:/configs"
    environment:
      MONGODB_ADMIN_USER              : root
      MONGODB_ADMIN_PASS              : storage
      MONGODB_APPLICATION_DATABASE    : umcft
      MONGODB_APPLICATION_USER        : storage
      MONGODB_APPLICATION_PASS        : storage
      MONGODB_PORT                    : "27018"
      MONGODB_USE_SSL                 : "false"
      MONGODB_ROOT_CA                 : "rootCA.pem"
      MONGODB_CERTIFICATE             : "mongodb.pem"
