#################################################
# HA Redi + HaProxy deployment
#################################################
nameOverride: flowmanager-redis
fullnameOverride: flowmanager-redis

serviceAccount:
  create: true

rbac:
  create: true

haproxy:
  enabled: true
  readOnly:
    enabled: false
  replicas: 3
  annotations: {}
  resources: {}
  stickyBalancing: false

  timeout:
    connect: 4s
    server: 30s
    client: 30s
  securityContext:
    runAsUser: 1000
    fsGroup: 1000
    runAsNonRoot: true

  tolerations: []
  additionalAffinities: {}

## Redis specific configuration options
redis:
  port: 6379
  masterGroupName: flowmanager
  config:
    min-replicas-to-write: 1
    min-replicas-max-lag: 5   # Value in seconds
    maxmemory: "0"       # Max memory to use for each redis instance. Default is unlimited.
    maxmemory-policy: "volatile-lru"  # Max memory policy to use for each redis instance. Default is volatile-lru.
    save: "900 1"
    repl-diskless-sync: "yes"
    rdbcompression: "yes"
    rdbchecksum: "yes"

  resources: 
    requests:
      memory: 200Mi
      cpu: 100m
    limits:
      memory: 700Mi

## Sentinel specific configuration options
sentinel:
  port: 26379
  quorum: 2
  config:
    down-after-milliseconds: 10000
    failover-timeout: 180000
    parallel-syncs: 5

  resources: 
    requests:
      memory: 200Mi
      cpu: 100m
    limits:
      memory: 200Mi

nodeSelector: {}
hardAntiAffinity: true
tolerations: []
additionalAffinities: {}

podDisruptionBudget: {}

## Configures redis with AUTH (requirepass & masterauth conf params)
auth: true
redisPassword: '5dmInP5ssw0rd'

## Use existing secret containing key `authKey` (ignores redisPassword)
# existingSecret:

## Defines the key holding the redis password in existing secret.
authKey: auth

persistentVolume:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 10Gi
  annotations: {}
init:
  resources: {}
hostPath:
  chown: true

